-- Adding state column to cities
ALTER TABLE "public"."cities" ADD COLUMN IF NOT EXISTS "state" text NOT NULL DEFAULT 'Other';

-- Truncate existing data to load the official state-district map
TRUNCATE TABLE "public"."cities";

-- Insert new data
INSERT INTO "public"."cities" ("name", "slug", "state", "is_active", "sort_order") VALUES
('Anantapur', 'anantapur', 'Andhra Pradesh', true, 1),
('Chittoor', 'chittoor', 'Andhra Pradesh', true, 2),
('East Godavari', 'east-godavari', 'Andhra Pradesh', true, 3),
('Guntur', 'guntur', 'Andhra Pradesh', true, 4),
('Krishna', 'krishna', 'Andhra Pradesh', true, 5),
('Kurnool', 'kurnool', 'Andhra Pradesh', true, 6),
('Nellore', 'nellore', 'Andhra Pradesh', true, 7),
('Prakasam', 'prakasam', 'Andhra Pradesh', true, 8),
('Srikakulam', 'srikakulam', 'Andhra Pradesh', true, 9),
('Visakhapatnam', 'visakhapatnam', 'Andhra Pradesh', true, 10),
('Vizianagaram', 'vizianagaram', 'Andhra Pradesh', true, 11),
('West Godavari', 'west-godavari', 'Andhra Pradesh', true, 12),
('YSR Kadapa', 'ysr-kadapa', 'Andhra Pradesh', true, 13),
('Tawang', 'tawang', 'Arunachal Pradesh', true, 14),
('West Kameng', 'west-kameng', 'Arunachal Pradesh', true, 15),
('East Kameng', 'east-kameng', 'Arunachal Pradesh', true, 16),
('Papum Pare', 'papum-pare', 'Arunachal Pradesh', true, 17),
('Kurung Kumey', 'kurung-kumey', 'Arunachal Pradesh', true, 18),
('Kra Daadi', 'kra-daadi', 'Arunachal Pradesh', true, 19),
('Lower Subansiri', 'lower-subansiri', 'Arunachal Pradesh', true, 20),
('Upper Subansiri', 'upper-subansiri', 'Arunachal Pradesh', true, 21),
('West Siang', 'west-siang', 'Arunachal Pradesh', true, 22),
('East Siang', 'east-siang', 'Arunachal Pradesh', true, 23),
('Siang', 'siang', 'Arunachal Pradesh', true, 24),
('Upper Siang', 'upper-siang', 'Arunachal Pradesh', true, 25),
('Lower Siang', 'lower-siang', 'Arunachal Pradesh', true, 26),
('Lower Dibang Valley', 'lower-dibang-valley', 'Arunachal Pradesh', true, 27),
('Dibang Valley', 'dibang-valley', 'Arunachal Pradesh', true, 28),
('Anjaw', 'anjaw', 'Arunachal Pradesh', true, 29),
('Lohit', 'lohit', 'Arunachal Pradesh', true, 30),
('Namsai', 'namsai', 'Arunachal Pradesh', true, 31),
('Changlang', 'changlang', 'Arunachal Pradesh', true, 32),
('Tirap', 'tirap', 'Arunachal Pradesh', true, 33),
('Longding', 'longding', 'Arunachal Pradesh', true, 34),
('Baksa', 'baksa', 'Assam', true, 35),
('Barpeta', 'barpeta', 'Assam', true, 36),
('Biswanath', 'biswanath', 'Assam', true, 37),
('Bongaigaon', 'bongaigaon', 'Assam', true, 38),
('Cachar', 'cachar', 'Assam', true, 39),
('Charaideo', 'charaideo', 'Assam', true, 40),
('Chirang', 'chirang', 'Assam', true, 41),
('Darrang', 'darrang', 'Assam', true, 42),
('Dhemaji', 'dhemaji', 'Assam', true, 43),
('Dhubri', 'dhubri', 'Assam', true, 44),
('Dibrugarh', 'dibrugarh', 'Assam', true, 45),
('Goalpara', 'goalpara', 'Assam', true, 46),
('Golaghat', 'golaghat', 'Assam', true, 47),
('Hailakandi', 'hailakandi', 'Assam', true, 48),
('Hojai', 'hojai', 'Assam', true, 49),
('Jorhat', 'jorhat', 'Assam', true, 50),
('Kamrup Metropolitan', 'kamrup-metropolitan', 'Assam', true, 51),
('Kamrup', 'kamrup', 'Assam', true, 52),
('Karbi Anglong', 'karbi-anglong', 'Assam', true, 53),
('Karimganj', 'karimganj', 'Assam', true, 54),
('Kokrajhar', 'kokrajhar', 'Assam', true, 55),
('Lakhimpur', 'lakhimpur', 'Assam', true, 56),
('Majuli', 'majuli', 'Assam', true, 57),
('Morigaon', 'morigaon', 'Assam', true, 58),
('Nagaon', 'nagaon', 'Assam', true, 59),
('Nalbari', 'nalbari', 'Assam', true, 60),
('Dima Hasao', 'dima-hasao', 'Assam', true, 61),
('Sivasagar', 'sivasagar', 'Assam', true, 62),
('Sonitpur', 'sonitpur', 'Assam', true, 63),
('South Salmara-Mankachar', 'south-salmara-mankachar', 'Assam', true, 64),
('Tinsukia', 'tinsukia', 'Assam', true, 65),
('Udalguri', 'udalguri', 'Assam', true, 66),
('West Karbi Anglong', 'west-karbi-anglong', 'Assam', true, 67),
('Araria', 'araria', 'Bihar', true, 68),
('Arwal', 'arwal', 'Bihar', true, 69),
('Aurangabad (Bihar)', 'aurangabad-bihar', 'Bihar', true, 70),
('Banka', 'banka', 'Bihar', true, 71),
('Begusarai', 'begusarai', 'Bihar', true, 72),
('Bhagalpur', 'bhagalpur', 'Bihar', true, 73),
('Bhojpur', 'bhojpur', 'Bihar', true, 74),
('Buxar', 'buxar', 'Bihar', true, 75),
('Darbhanga', 'darbhanga', 'Bihar', true, 76),
('East Champaran (Motihari)', 'east-champaran-motihari-', 'Bihar', true, 77),
('Gaya', 'gaya', 'Bihar', true, 78),
('Gopalganj', 'gopalganj', 'Bihar', true, 79),
('Jamui', 'jamui', 'Bihar', true, 80),
('Jehanabad', 'jehanabad', 'Bihar', true, 81),
('Kaimur (Bhabua)', 'kaimur-bhabua-', 'Bihar', true, 82),
('Katihar', 'katihar', 'Bihar', true, 83),
('Khagaria', 'khagaria', 'Bihar', true, 84),
('Kishanganj', 'kishanganj', 'Bihar', true, 85),
('Lakhisarai', 'lakhisarai', 'Bihar', true, 86),
('Madhepura', 'madhepura', 'Bihar', true, 87),
('Madhubani', 'madhubani', 'Bihar', true, 88),
('Munger (Monghyr)', 'munger-monghyr-', 'Bihar', true, 89),
('Muzaffarpur', 'muzaffarpur', 'Bihar', true, 90),
('Nalanda', 'nalanda', 'Bihar', true, 91),
('Nawada', 'nawada', 'Bihar', true, 92),
('Patna', 'patna', 'Bihar', true, 93),
('Purnia (Purnea)', 'purnia-purnea-', 'Bihar', true, 94),
('Rohtas', 'rohtas', 'Bihar', true, 95),
('Saharsa', 'saharsa', 'Bihar', true, 96),
('Samastipur', 'samastipur', 'Bihar', true, 97),
('Saran', 'saran', 'Bihar', true, 98),
('Sheikhpura', 'sheikhpura', 'Bihar', true, 99),
('Sheohar', 'sheohar', 'Bihar', true, 100),
('Sitamarhi', 'sitamarhi', 'Bihar', true, 101),
('Siwan', 'siwan', 'Bihar', true, 102),
('Supaul', 'supaul', 'Bihar', true, 103),
('Vaishali', 'vaishali', 'Bihar', true, 104),
('West Champaran', 'west-champaran', 'Bihar', true, 105),
('Chandigarh', 'chandigarh', 'Chandigarh (UT)', true, 106),
('Balod', 'balod', 'Chhattisgarh', true, 107),
('Baloda Bazar', 'baloda-bazar', 'Chhattisgarh', true, 108),
('Balrampur (Chhattisgarh)', 'balrampur-chhattisgarh', 'Chhattisgarh', true, 109),
('Bastar', 'bastar', 'Chhattisgarh', true, 110),
('Bemetara', 'bemetara', 'Chhattisgarh', true, 111),
('Bijapur', 'bijapur', 'Chhattisgarh', true, 112),
('Bilaspur (Chhattisgarh)', 'bilaspur-chhattisgarh', 'Chhattisgarh', true, 113),
('Dantewada (South Bastar)', 'dantewada-south-bastar-', 'Chhattisgarh', true, 114),
('Dhamtari', 'dhamtari', 'Chhattisgarh', true, 115),
('Durg', 'durg', 'Chhattisgarh', true, 116),
('Gariyaband', 'gariyaband', 'Chhattisgarh', true, 117),
('Janjgir-Champa', 'janjgir-champa', 'Chhattisgarh', true, 118),
('Jashpur', 'jashpur', 'Chhattisgarh', true, 119),
('Kabirdham (Kawardha)', 'kabirdham-kawardha-', 'Chhattisgarh', true, 120),
('Kanker (North Bastar)', 'kanker-north-bastar-', 'Chhattisgarh', true, 121),
('Kondagaon', 'kondagaon', 'Chhattisgarh', true, 122),
('Korba', 'korba', 'Chhattisgarh', true, 123),
('Korea (Koriya)', 'korea-koriya-', 'Chhattisgarh', true, 124),
('Mahasamund', 'mahasamund', 'Chhattisgarh', true, 125),
('Mungeli', 'mungeli', 'Chhattisgarh', true, 126),
('Narayanpur', 'narayanpur', 'Chhattisgarh', true, 127),
('Raigarh', 'raigarh', 'Chhattisgarh', true, 128),
('Raipur', 'raipur', 'Chhattisgarh', true, 129),
('Rajnandgaon', 'rajnandgaon', 'Chhattisgarh', true, 130),
('Sukma', 'sukma', 'Chhattisgarh', true, 131),
('Surajpur  ', 'surajpur-', 'Chhattisgarh', true, 132),
('Surguja', 'surguja', 'Chhattisgarh', true, 133),
('Dadra & Nagar Haveli', 'dadra-nagar-haveli', 'Dadra and Nagar Haveli (UT)', true, 134),
('Daman', 'daman', 'Daman and Diu (UT)', true, 135),
('Diu', 'diu', 'Daman and Diu (UT)', true, 136),
('Central Delhi', 'central-delhi', 'Delhi (NCT)', true, 137),
('East Delhi', 'east-delhi', 'Delhi (NCT)', true, 138),
('New Delhi', 'new-delhi', 'Delhi (NCT)', true, 139),
('North Delhi', 'north-delhi', 'Delhi (NCT)', true, 140),
('North East  Delhi', 'north-east-delhi', 'Delhi (NCT)', true, 141),
('North West  Delhi', 'north-west-delhi', 'Delhi (NCT)', true, 142),
('Shahdara', 'shahdara', 'Delhi (NCT)', true, 143),
('South Delhi', 'south-delhi', 'Delhi (NCT)', true, 144),
('South East Delhi', 'south-east-delhi', 'Delhi (NCT)', true, 145),
('South West  Delhi', 'south-west-delhi', 'Delhi (NCT)', true, 146),
('West Delhi', 'west-delhi', 'Delhi (NCT)', true, 147),
('North Goa', 'north-goa', 'Goa', true, 148),
('South Goa', 'south-goa', 'Goa', true, 149),
('Ahmedabad', 'ahmedabad', 'Gujarat', true, 150),
('Amreli', 'amreli', 'Gujarat', true, 151),
('Anand', 'anand', 'Gujarat', true, 152),
('Aravalli', 'aravalli', 'Gujarat', true, 153),
('Banaskantha (Palanpur)', 'banaskantha-palanpur-', 'Gujarat', true, 154),
('Bharuch', 'bharuch', 'Gujarat', true, 155),
('Bhavnagar', 'bhavnagar', 'Gujarat', true, 156),
('Botad', 'botad', 'Gujarat', true, 157),
('Chhota Udepur', 'chhota-udepur', 'Gujarat', true, 158),
('Dahod', 'dahod', 'Gujarat', true, 159),
('Dangs (Ahwa)', 'dangs-ahwa-', 'Gujarat', true, 160),
('Devbhoomi Dwarka', 'devbhoomi-dwarka', 'Gujarat', true, 161),
('Gandhinagar', 'gandhinagar', 'Gujarat', true, 162),
('Gir Somnath', 'gir-somnath', 'Gujarat', true, 163),
('Jamnagar', 'jamnagar', 'Gujarat', true, 164),
('Junagadh', 'junagadh', 'Gujarat', true, 165),
('Kachchh', 'kachchh', 'Gujarat', true, 166),
('Kheda (Nadiad)', 'kheda-nadiad-', 'Gujarat', true, 167),
('Mahisagar', 'mahisagar', 'Gujarat', true, 168),
('Mehsana', 'mehsana', 'Gujarat', true, 169),
('Morbi', 'morbi', 'Gujarat', true, 170),
('Narmada (Rajpipla)', 'narmada-rajpipla-', 'Gujarat', true, 171),
('Navsari', 'navsari', 'Gujarat', true, 172),
('Panchmahal (Godhra)', 'panchmahal-godhra-', 'Gujarat', true, 173),
('Patan', 'patan', 'Gujarat', true, 174),
('Porbandar', 'porbandar', 'Gujarat', true, 175),
('Rajkot', 'rajkot', 'Gujarat', true, 176),
('Sabarkantha (Himmatnagar)', 'sabarkantha-himmatnagar-', 'Gujarat', true, 177),
('Surat', 'surat', 'Gujarat', true, 178),
('Surendranagar', 'surendranagar', 'Gujarat', true, 179),
('Tapi (Vyara)', 'tapi-vyara-', 'Gujarat', true, 180),
('Vadodara', 'vadodara', 'Gujarat', true, 181),
('Valsad', 'valsad', 'Gujarat', true, 182),
('Ambala', 'ambala', 'Haryana', true, 183),
('Bhiwani', 'bhiwani', 'Haryana', true, 184),
('Charkhi Dadri', 'charkhi-dadri', 'Haryana', true, 185),
('Faridabad', 'faridabad', 'Haryana', true, 186),
('Fatehabad', 'fatehabad', 'Haryana', true, 187),
('Gurgaon', 'gurgaon', 'Haryana', true, 188),
('Hisar', 'hisar', 'Haryana', true, 189),
('Jhajjar', 'jhajjar', 'Haryana', true, 190),
('Jind', 'jind', 'Haryana', true, 191),
('Kaithal', 'kaithal', 'Haryana', true, 192),
('Karnal', 'karnal', 'Haryana', true, 193),
('Kurukshetra', 'kurukshetra', 'Haryana', true, 194),
('Mahendragarh', 'mahendragarh', 'Haryana', true, 195),
('Mewat', 'mewat', 'Haryana', true, 196),
('Palwal', 'palwal', 'Haryana', true, 197),
('Panchkula', 'panchkula', 'Haryana', true, 198),
('Panipat', 'panipat', 'Haryana', true, 199),
('Rewari', 'rewari', 'Haryana', true, 200),
('Rohtak', 'rohtak', 'Haryana', true, 201),
('Sirsa', 'sirsa', 'Haryana', true, 202),
('Sonipat', 'sonipat', 'Haryana', true, 203),
('Yamunanagar', 'yamunanagar', 'Haryana', true, 204),
('Bilaspur (HP)', 'bilaspur-hp', 'Himachal Pradesh', true, 205),
('Chamba', 'chamba', 'Himachal Pradesh', true, 206),
('Hamirpur (HP)', 'hamirpur-hp', 'Himachal Pradesh', true, 207),
('Kangra', 'kangra', 'Himachal Pradesh', true, 208),
('Kinnaur', 'kinnaur', 'Himachal Pradesh', true, 209),
('Kullu', 'kullu', 'Himachal Pradesh', true, 210),
('Lahaul &amp; Spiti', 'lahaul-amp-spiti', 'Himachal Pradesh', true, 211),
('Mandi', 'mandi', 'Himachal Pradesh', true, 212),
('Shimla', 'shimla', 'Himachal Pradesh', true, 213),
('Sirmaur (Sirmour)', 'sirmaur-sirmour-', 'Himachal Pradesh', true, 214),
('Solan', 'solan', 'Himachal Pradesh', true, 215),
('Una', 'una', 'Himachal Pradesh', true, 216),
('Anantnag', 'anantnag', 'Jammu and Kashmir', true, 217),
('Bandipore', 'bandipore', 'Jammu and Kashmir', true, 218),
('Baramulla', 'baramulla', 'Jammu and Kashmir', true, 219),
('Budgam', 'budgam', 'Jammu and Kashmir', true, 220),
('Doda', 'doda', 'Jammu and Kashmir', true, 221),
('Ganderbal', 'ganderbal', 'Jammu and Kashmir', true, 222),
('Jammu', 'jammu', 'Jammu and Kashmir', true, 223),
('Kargil', 'kargil', 'Jammu and Kashmir', true, 224),
('Kathua', 'kathua', 'Jammu and Kashmir', true, 225),
('Kishtwar', 'kishtwar', 'Jammu and Kashmir', true, 226),
('Kulgam', 'kulgam', 'Jammu and Kashmir', true, 227),
('Kupwara', 'kupwara', 'Jammu and Kashmir', true, 228),
('Leh', 'leh', 'Jammu and Kashmir', true, 229),
('Poonch', 'poonch', 'Jammu and Kashmir', true, 230),
('Pulwama', 'pulwama', 'Jammu and Kashmir', true, 231),
('Rajouri', 'rajouri', 'Jammu and Kashmir', true, 232),
('Ramban', 'ramban', 'Jammu and Kashmir', true, 233),
('Reasi', 'reasi', 'Jammu and Kashmir', true, 234),
('Samba', 'samba', 'Jammu and Kashmir', true, 235),
('Shopian', 'shopian', 'Jammu and Kashmir', true, 236),
('Srinagar', 'srinagar', 'Jammu and Kashmir', true, 237),
('Udhampur', 'udhampur', 'Jammu and Kashmir', true, 238),
('Bokaro', 'bokaro', 'Jharkhand', true, 239),
('Chatra', 'chatra', 'Jharkhand', true, 240),
('Deoghar', 'deoghar', 'Jharkhand', true, 241),
('Dhanbad', 'dhanbad', 'Jharkhand', true, 242),
('Dumka', 'dumka', 'Jharkhand', true, 243),
('East Singhbhum', 'east-singhbhum', 'Jharkhand', true, 244),
('Garhwa', 'garhwa', 'Jharkhand', true, 245),
('Giridih', 'giridih', 'Jharkhand', true, 246),
('Godda', 'godda', 'Jharkhand', true, 247),
('Gumla', 'gumla', 'Jharkhand', true, 248),
('Hazaribag', 'hazaribag', 'Jharkhand', true, 249),
('Jamtara', 'jamtara', 'Jharkhand', true, 250),
('Khunti', 'khunti', 'Jharkhand', true, 251),
('Koderma', 'koderma', 'Jharkhand', true, 252),
('Latehar', 'latehar', 'Jharkhand', true, 253),
('Lohardaga', 'lohardaga', 'Jharkhand', true, 254),
('Pakur', 'pakur', 'Jharkhand', true, 255),
('Palamu', 'palamu', 'Jharkhand', true, 256),
('Ramgarh', 'ramgarh', 'Jharkhand', true, 257),
('Ranchi', 'ranchi', 'Jharkhand', true, 258),
('Sahibganj', 'sahibganj', 'Jharkhand', true, 259),
('Seraikela-Kharsawan', 'seraikela-kharsawan', 'Jharkhand', true, 260),
('Simdega', 'simdega', 'Jharkhand', true, 261),
('West Singhbhum', 'west-singhbhum', 'Jharkhand', true, 262),
('Bagalkot', 'bagalkot', 'Karnataka', true, 263),
('Ballari (Bellary)', 'ballari-bellary-', 'Karnataka', true, 264),
('Belagavi (Belgaum)', 'belagavi-belgaum-', 'Karnataka', true, 265),
('Bengaluru (Bangalore) Rural', 'bengaluru-bangalore-rural', 'Karnataka', true, 266),
('Bengaluru (Bangalore) Urban', 'bengaluru-bangalore-urban', 'Karnataka', true, 267),
('Bidar', 'bidar', 'Karnataka', true, 268),
('Chamarajanagar', 'chamarajanagar', 'Karnataka', true, 269),
('Chikballapur', 'chikballapur', 'Karnataka', true, 270),
('Chikkamagaluru (Chikmagalur)', 'chikkamagaluru-chikmagalur-', 'Karnataka', true, 271),
('Chitradurga', 'chitradurga', 'Karnataka', true, 272),
('Dakshina Kannada', 'dakshina-kannada', 'Karnataka', true, 273),
('Davangere', 'davangere', 'Karnataka', true, 274),
('Dharwad', 'dharwad', 'Karnataka', true, 275),
('Gadag', 'gadag', 'Karnataka', true, 276),
('Hassan', 'hassan', 'Karnataka', true, 277),
('Haveri', 'haveri', 'Karnataka', true, 278),
('Kalaburagi (Gulbarga)', 'kalaburagi-gulbarga-', 'Karnataka', true, 279),
('Kodagu', 'kodagu', 'Karnataka', true, 280),
('Kolar', 'kolar', 'Karnataka', true, 281),
('Koppal', 'koppal', 'Karnataka', true, 282),
('Mandya', 'mandya', 'Karnataka', true, 283),
('Mysuru (Mysore)', 'mysuru-mysore-', 'Karnataka', true, 284),
('Raichur', 'raichur', 'Karnataka', true, 285),
('Ramanagara', 'ramanagara', 'Karnataka', true, 286),
('Shivamogga (Shimoga)', 'shivamogga-shimoga-', 'Karnataka', true, 287),
('Tumakuru (Tumkur)', 'tumakuru-tumkur-', 'Karnataka', true, 288),
('Udupi', 'udupi', 'Karnataka', true, 289),
('Uttara Kannada (Karwar)', 'uttara-kannada-karwar-', 'Karnataka', true, 290),
('Vijayapura (Bijapur)', 'vijayapura-bijapur-', 'Karnataka', true, 291),
('Yadgir', 'yadgir', 'Karnataka', true, 292),
('Alappuzha', 'alappuzha', 'Kerala', true, 293),
('Ernakulam', 'ernakulam', 'Kerala', true, 294),
('Idukki', 'idukki', 'Kerala', true, 295),
('Kannur', 'kannur', 'Kerala', true, 296),
('Kasaragod', 'kasaragod', 'Kerala', true, 297),
('Kollam', 'kollam', 'Kerala', true, 298),
('Kottayam', 'kottayam', 'Kerala', true, 299),
('Kozhikode', 'kozhikode', 'Kerala', true, 300),
('Malappuram', 'malappuram', 'Kerala', true, 301),
('Palakkad', 'palakkad', 'Kerala', true, 302),
('Pathanamthitta', 'pathanamthitta', 'Kerala', true, 303),
('Thiruvananthapuram', 'thiruvananthapuram', 'Kerala', true, 304),
('Thrissur', 'thrissur', 'Kerala', true, 305),
('Wayanad', 'wayanad', 'Kerala', true, 306),
('Agatti', 'agatti', 'Lakshadweep (UT)', true, 307),
('Amini', 'amini', 'Lakshadweep (UT)', true, 308),
('Androth', 'androth', 'Lakshadweep (UT)', true, 309),
('Bithra', 'bithra', 'Lakshadweep (UT)', true, 310),
('Chethlath', 'chethlath', 'Lakshadweep (UT)', true, 311),
('Kavaratti', 'kavaratti', 'Lakshadweep (UT)', true, 312),
('Kadmath', 'kadmath', 'Lakshadweep (UT)', true, 313),
('Kalpeni', 'kalpeni', 'Lakshadweep (UT)', true, 314),
('Kilthan', 'kilthan', 'Lakshadweep (UT)', true, 315),
('Minicoy', 'minicoy', 'Lakshadweep (UT)', true, 316),
('Agar Malwa', 'agar-malwa', 'Madhya Pradesh', true, 317),
('Alirajpur', 'alirajpur', 'Madhya Pradesh', true, 318),
('Anuppur', 'anuppur', 'Madhya Pradesh', true, 319),
('Ashoknagar', 'ashoknagar', 'Madhya Pradesh', true, 320),
('Balaghat', 'balaghat', 'Madhya Pradesh', true, 321),
('Barwani', 'barwani', 'Madhya Pradesh', true, 322),
('Betul', 'betul', 'Madhya Pradesh', true, 323),
('Bhind', 'bhind', 'Madhya Pradesh', true, 324),
('Bhopal', 'bhopal', 'Madhya Pradesh', true, 325),
('Burhanpur', 'burhanpur', 'Madhya Pradesh', true, 326),
('Chhatarpur', 'chhatarpur', 'Madhya Pradesh', true, 327),
('Chhindwara', 'chhindwara', 'Madhya Pradesh', true, 328),
('Damoh', 'damoh', 'Madhya Pradesh', true, 329),
('Datia', 'datia', 'Madhya Pradesh', true, 330),
('Dewas', 'dewas', 'Madhya Pradesh', true, 331),
('Dhar', 'dhar', 'Madhya Pradesh', true, 332),
('Dindori', 'dindori', 'Madhya Pradesh', true, 333),
('Guna', 'guna', 'Madhya Pradesh', true, 334),
('Gwalior', 'gwalior', 'Madhya Pradesh', true, 335),
('Harda', 'harda', 'Madhya Pradesh', true, 336),
('Hoshangabad', 'hoshangabad', 'Madhya Pradesh', true, 337),
('Indore', 'indore', 'Madhya Pradesh', true, 338),
('Jabalpur', 'jabalpur', 'Madhya Pradesh', true, 339),
('Jhabua', 'jhabua', 'Madhya Pradesh', true, 340),
('Katni', 'katni', 'Madhya Pradesh', true, 341),
('Khandwa', 'khandwa', 'Madhya Pradesh', true, 342),
('Khargone', 'khargone', 'Madhya Pradesh', true, 343),
('Mandla', 'mandla', 'Madhya Pradesh', true, 344),
('Mandsaur', 'mandsaur', 'Madhya Pradesh', true, 345),
('Morena', 'morena', 'Madhya Pradesh', true, 346),
('Narsinghpur', 'narsinghpur', 'Madhya Pradesh', true, 347),
('Neemuch', 'neemuch', 'Madhya Pradesh', true, 348),
('Panna', 'panna', 'Madhya Pradesh', true, 349),
('Raisen', 'raisen', 'Madhya Pradesh', true, 350),
('Rajgarh', 'rajgarh', 'Madhya Pradesh', true, 351),
('Ratlam', 'ratlam', 'Madhya Pradesh', true, 352),
('Rewa', 'rewa', 'Madhya Pradesh', true, 353),
('Sagar', 'sagar', 'Madhya Pradesh', true, 354),
('Satna', 'satna', 'Madhya Pradesh', true, 355),
('Sehore', 'sehore', 'Madhya Pradesh', true, 356),
('Seoni', 'seoni', 'Madhya Pradesh', true, 357),
('Shahdol', 'shahdol', 'Madhya Pradesh', true, 358),
('Shajapur', 'shajapur', 'Madhya Pradesh', true, 359),
('Sheopur', 'sheopur', 'Madhya Pradesh', true, 360),
('Shivpuri', 'shivpuri', 'Madhya Pradesh', true, 361),
('Sidhi', 'sidhi', 'Madhya Pradesh', true, 362),
('Singrauli', 'singrauli', 'Madhya Pradesh', true, 363),
('Tikamgarh', 'tikamgarh', 'Madhya Pradesh', true, 364),
('Ujjain', 'ujjain', 'Madhya Pradesh', true, 365),
('Umaria', 'umaria', 'Madhya Pradesh', true, 366),
('Vidisha', 'vidisha', 'Madhya Pradesh', true, 367),
('Ahmednagar', 'ahmednagar', 'Maharashtra', true, 368),
('Akola', 'akola', 'Maharashtra', true, 369),
('Amravati', 'amravati', 'Maharashtra', true, 370),
('Aurangabad (Maharashtra)', 'aurangabad-maharashtra', 'Maharashtra', true, 371),
('Beed', 'beed', 'Maharashtra', true, 372),
('Bhandara', 'bhandara', 'Maharashtra', true, 373),
('Buldhana', 'buldhana', 'Maharashtra', true, 374),
('Chandrapur', 'chandrapur', 'Maharashtra', true, 375),
('Dhule', 'dhule', 'Maharashtra', true, 376),
('Gadchiroli', 'gadchiroli', 'Maharashtra', true, 377),
('Gondia', 'gondia', 'Maharashtra', true, 378),
('Hingoli', 'hingoli', 'Maharashtra', true, 379),
('Jalgaon', 'jalgaon', 'Maharashtra', true, 380),
('Jalna', 'jalna', 'Maharashtra', true, 381),
('Kolhapur', 'kolhapur', 'Maharashtra', true, 382),
('Latur', 'latur', 'Maharashtra', true, 383),
('Mumbai City', 'mumbai-city', 'Maharashtra', true, 384),
('Mumbai Suburban', 'mumbai-suburban', 'Maharashtra', true, 385),
('Nagpur', 'nagpur', 'Maharashtra', true, 386),
('Nanded', 'nanded', 'Maharashtra', true, 387),
('Nandurbar', 'nandurbar', 'Maharashtra', true, 388),
('Nashik', 'nashik', 'Maharashtra', true, 389),
('Osmanabad', 'osmanabad', 'Maharashtra', true, 390),
('Palghar', 'palghar', 'Maharashtra', true, 391),
('Parbhani', 'parbhani', 'Maharashtra', true, 392),
('Pune', 'pune', 'Maharashtra', true, 393),
('Raigad', 'raigad', 'Maharashtra', true, 394),
('Ratnagiri', 'ratnagiri', 'Maharashtra', true, 395),
('Sangli', 'sangli', 'Maharashtra', true, 396),
('Satara', 'satara', 'Maharashtra', true, 397),
('Sindhudurg', 'sindhudurg', 'Maharashtra', true, 398),
('Solapur', 'solapur', 'Maharashtra', true, 399),
('Thane', 'thane', 'Maharashtra', true, 400),
('Wardha', 'wardha', 'Maharashtra', true, 401),
('Washim', 'washim', 'Maharashtra', true, 402),
('Yavatmal', 'yavatmal', 'Maharashtra', true, 403),
('Bishnupur', 'bishnupur', 'Manipur', true, 404),
('Chandel', 'chandel', 'Manipur', true, 405),
('Churachandpur', 'churachandpur', 'Manipur', true, 406),
('Imphal East', 'imphal-east', 'Manipur', true, 407),
('Imphal West', 'imphal-west', 'Manipur', true, 408),
('Jiribam', 'jiribam', 'Manipur', true, 409),
('Kakching', 'kakching', 'Manipur', true, 410),
('Kamjong', 'kamjong', 'Manipur', true, 411),
('Kangpokpi', 'kangpokpi', 'Manipur', true, 412),
('Noney', 'noney', 'Manipur', true, 413),
('Pherzawl', 'pherzawl', 'Manipur', true, 414),
('Senapati', 'senapati', 'Manipur', true, 415),
('Tamenglong', 'tamenglong', 'Manipur', true, 416),
('Tengnoupal', 'tengnoupal', 'Manipur', true, 417),
('Thoubal', 'thoubal', 'Manipur', true, 418),
('Ukhrul', 'ukhrul', 'Manipur', true, 419),
('East Garo Hills', 'east-garo-hills', 'Meghalaya', true, 420),
('East Jaintia Hills', 'east-jaintia-hills', 'Meghalaya', true, 421),
('East Khasi Hills', 'east-khasi-hills', 'Meghalaya', true, 422),
('North Garo Hills', 'north-garo-hills', 'Meghalaya', true, 423),
('Ri Bhoi', 'ri-bhoi', 'Meghalaya', true, 424),
('South Garo Hills', 'south-garo-hills', 'Meghalaya', true, 425),
('South West Garo Hills ', 'south-west-garo-hills-', 'Meghalaya', true, 426),
('South West Khasi Hills', 'south-west-khasi-hills', 'Meghalaya', true, 427),
('West Garo Hills', 'west-garo-hills', 'Meghalaya', true, 428),
('West Jaintia Hills', 'west-jaintia-hills', 'Meghalaya', true, 429),
('West Khasi Hills', 'west-khasi-hills', 'Meghalaya', true, 430),
('Aizawl', 'aizawl', 'Mizoram', true, 431),
('Champhai', 'champhai', 'Mizoram', true, 432),
('Kolasib', 'kolasib', 'Mizoram', true, 433),
('Lawngtlai', 'lawngtlai', 'Mizoram', true, 434),
('Lunglei', 'lunglei', 'Mizoram', true, 435),
('Mamit', 'mamit', 'Mizoram', true, 436),
('Saiha', 'saiha', 'Mizoram', true, 437),
('Serchhip', 'serchhip', 'Mizoram', true, 438),
('Dimapur', 'dimapur', 'Nagaland', true, 439),
('Kiphire', 'kiphire', 'Nagaland', true, 440),
('Kohima', 'kohima', 'Nagaland', true, 441),
('Longleng', 'longleng', 'Nagaland', true, 442),
('Mokokchung', 'mokokchung', 'Nagaland', true, 443),
('Mon', 'mon', 'Nagaland', true, 444),
('Peren', 'peren', 'Nagaland', true, 445),
('Phek', 'phek', 'Nagaland', true, 446),
('Tuensang', 'tuensang', 'Nagaland', true, 447),
('Wokha', 'wokha', 'Nagaland', true, 448),
('Zunheboto', 'zunheboto', 'Nagaland', true, 449),
('Angul', 'angul', 'Odisha', true, 450),
('Balangir', 'balangir', 'Odisha', true, 451),
('Balasore', 'balasore', 'Odisha', true, 452),
('Bargarh', 'bargarh', 'Odisha', true, 453),
('Bhadrak', 'bhadrak', 'Odisha', true, 454),
('Boudh', 'boudh', 'Odisha', true, 455),
('Cuttack', 'cuttack', 'Odisha', true, 456),
('Deogarh', 'deogarh', 'Odisha', true, 457),
('Dhenkanal', 'dhenkanal', 'Odisha', true, 458),
('Gajapati', 'gajapati', 'Odisha', true, 459),
('Ganjam', 'ganjam', 'Odisha', true, 460),
('Jagatsinghapur', 'jagatsinghapur', 'Odisha', true, 461),
('Jajpur', 'jajpur', 'Odisha', true, 462),
('Jharsuguda', 'jharsuguda', 'Odisha', true, 463),
('Kalahandi', 'kalahandi', 'Odisha', true, 464),
('Kandhamal', 'kandhamal', 'Odisha', true, 465),
('Kendrapara', 'kendrapara', 'Odisha', true, 466),
('Kendujhar (Keonjhar)', 'kendujhar-keonjhar-', 'Odisha', true, 467),
('Khordha', 'khordha', 'Odisha', true, 468),
('Koraput', 'koraput', 'Odisha', true, 469),
('Malkangiri', 'malkangiri', 'Odisha', true, 470),
('Mayurbhanj', 'mayurbhanj', 'Odisha', true, 471),
('Nabarangpur', 'nabarangpur', 'Odisha', true, 472),
('Nayagarh', 'nayagarh', 'Odisha', true, 473),
('Nuapada', 'nuapada', 'Odisha', true, 474),
('Puri', 'puri', 'Odisha', true, 475),
('Rayagada', 'rayagada', 'Odisha', true, 476),
('Sambalpur', 'sambalpur', 'Odisha', true, 477),
('Sonepur', 'sonepur', 'Odisha', true, 478),
('Sundargarh', 'sundargarh', 'Odisha', true, 479),
('Karaikal', 'karaikal', 'Puducherry (UT)', true, 480),
('Mahe', 'mahe', 'Puducherry (UT)', true, 481),
('Pondicherry', 'pondicherry', 'Puducherry (UT)', true, 482),
('Yanam', 'yanam', 'Puducherry (UT)', true, 483),
('Amritsar', 'amritsar', 'Punjab', true, 484),
('Barnala', 'barnala', 'Punjab', true, 485),
('Bathinda', 'bathinda', 'Punjab', true, 486),
('Faridkot', 'faridkot', 'Punjab', true, 487),
('Fatehgarh Sahib', 'fatehgarh-sahib', 'Punjab', true, 488),
('Fazilka', 'fazilka', 'Punjab', true, 489),
('Ferozepur', 'ferozepur', 'Punjab', true, 490),
('Gurdaspur', 'gurdaspur', 'Punjab', true, 491),
('Hoshiarpur', 'hoshiarpur', 'Punjab', true, 492),
('Jalandhar', 'jalandhar', 'Punjab', true, 493),
('Kapurthala', 'kapurthala', 'Punjab', true, 494),
('Ludhiana', 'ludhiana', 'Punjab', true, 495),
('Mansa', 'mansa', 'Punjab', true, 496),
('Moga', 'moga', 'Punjab', true, 497),
('Muktsar', 'muktsar', 'Punjab', true, 498),
('Nawanshahr (Shahid Bhagat Singh Nagar)', 'nawanshahr-shahid-bhagat-singh-nagar-', 'Punjab', true, 499),
('Pathankot', 'pathankot', 'Punjab', true, 500),
('Patiala', 'patiala', 'Punjab', true, 501),
('Rupnagar', 'rupnagar', 'Punjab', true, 502),
('Sahibzada Ajit Singh Nagar (Mohali)', 'sahibzada-ajit-singh-nagar-mohali-', 'Punjab', true, 503),
('Sangrur', 'sangrur', 'Punjab', true, 504),
('Tarn Taran', 'tarn-taran', 'Punjab', true, 505),
('Ajmer', 'ajmer', 'Rajasthan', true, 506),
('Alwar', 'alwar', 'Rajasthan', true, 507),
('Banswara', 'banswara', 'Rajasthan', true, 508),
('Baran', 'baran', 'Rajasthan', true, 509),
('Barmer', 'barmer', 'Rajasthan', true, 510),
('Bharatpur', 'bharatpur', 'Rajasthan', true, 511),
('Bhilwara', 'bhilwara', 'Rajasthan', true, 512),
('Bikaner', 'bikaner', 'Rajasthan', true, 513),
('Bundi', 'bundi', 'Rajasthan', true, 514),
('Chittorgarh', 'chittorgarh', 'Rajasthan', true, 515),
('Churu', 'churu', 'Rajasthan', true, 516),
('Dausa', 'dausa', 'Rajasthan', true, 517),
('Dholpur', 'dholpur', 'Rajasthan', true, 518),
('Dungarpur', 'dungarpur', 'Rajasthan', true, 519),
('Hanumangarh', 'hanumangarh', 'Rajasthan', true, 520),
('Jaipur', 'jaipur', 'Rajasthan', true, 521),
('Jaisalmer', 'jaisalmer', 'Rajasthan', true, 522),
('Jalore', 'jalore', 'Rajasthan', true, 523),
('Jhalawar', 'jhalawar', 'Rajasthan', true, 524),
('Jhunjhunu', 'jhunjhunu', 'Rajasthan', true, 525),
('Jodhpur', 'jodhpur', 'Rajasthan', true, 526),
('Karauli', 'karauli', 'Rajasthan', true, 527),
('Kota', 'kota', 'Rajasthan', true, 528),
('Nagaur', 'nagaur', 'Rajasthan', true, 529),
('Pali', 'pali', 'Rajasthan', true, 530),
('Pratapgarh (Rajasthan)', 'pratapgarh-rajasthan', 'Rajasthan', true, 531),
('Rajsamand', 'rajsamand', 'Rajasthan', true, 532),
('Sawai Madhopur', 'sawai-madhopur', 'Rajasthan', true, 533),
('Sikar', 'sikar', 'Rajasthan', true, 534),
('Sirohi', 'sirohi', 'Rajasthan', true, 535),
('Sri Ganganagar', 'sri-ganganagar', 'Rajasthan', true, 536),
('Tonk', 'tonk', 'Rajasthan', true, 537),
('Udaipur', 'udaipur', 'Rajasthan', true, 538),
('East Sikkim', 'east-sikkim', 'Sikkim', true, 539),
('North Sikkim', 'north-sikkim', 'Sikkim', true, 540),
('South Sikkim', 'south-sikkim', 'Sikkim', true, 541),
('West Sikkim', 'west-sikkim', 'Sikkim', true, 542),
('Ariyalur', 'ariyalur', 'Tamil Nadu', true, 543),
('Chennai', 'chennai', 'Tamil Nadu', true, 544),
('Coimbatore', 'coimbatore', 'Tamil Nadu', true, 545),
('Cuddalore', 'cuddalore', 'Tamil Nadu', true, 546),
('Dharmapuri', 'dharmapuri', 'Tamil Nadu', true, 547),
('Dindigul', 'dindigul', 'Tamil Nadu', true, 548),
('Erode', 'erode', 'Tamil Nadu', true, 549),
('Kanchipuram', 'kanchipuram', 'Tamil Nadu', true, 550),
('Kanyakumari', 'kanyakumari', 'Tamil Nadu', true, 551),
('Karur', 'karur', 'Tamil Nadu', true, 552),
('Krishnagiri', 'krishnagiri', 'Tamil Nadu', true, 553),
('Madurai', 'madurai', 'Tamil Nadu', true, 554),
('Nagapattinam', 'nagapattinam', 'Tamil Nadu', true, 555),
('Namakkal', 'namakkal', 'Tamil Nadu', true, 556),
('Nilgiris', 'nilgiris', 'Tamil Nadu', true, 557),
('Perambalur', 'perambalur', 'Tamil Nadu', true, 558),
('Pudukkottai', 'pudukkottai', 'Tamil Nadu', true, 559),
('Ramanathapuram', 'ramanathapuram', 'Tamil Nadu', true, 560),
('Salem', 'salem', 'Tamil Nadu', true, 561),
('Sivaganga', 'sivaganga', 'Tamil Nadu', true, 562),
('Thanjavur', 'thanjavur', 'Tamil Nadu', true, 563),
('Theni', 'theni', 'Tamil Nadu', true, 564),
('Thoothukudi (Tuticorin)', 'thoothukudi-tuticorin-', 'Tamil Nadu', true, 565),
('Tiruchirappalli', 'tiruchirappalli', 'Tamil Nadu', true, 566),
('Tirunelveli', 'tirunelveli', 'Tamil Nadu', true, 567),
('Tiruppur', 'tiruppur', 'Tamil Nadu', true, 568),
('Tiruvallur', 'tiruvallur', 'Tamil Nadu', true, 569),
('Tiruvannamalai', 'tiruvannamalai', 'Tamil Nadu', true, 570),
('Tiruvarur', 'tiruvarur', 'Tamil Nadu', true, 571),
('Vellore', 'vellore', 'Tamil Nadu', true, 572),
('Viluppuram', 'viluppuram', 'Tamil Nadu', true, 573),
('Virudhunagar', 'virudhunagar', 'Tamil Nadu', true, 574),
('Adilabad', 'adilabad', 'Telangana', true, 575),
('Bhadradri Kothagudem', 'bhadradri-kothagudem', 'Telangana', true, 576),
('Hyderabad', 'hyderabad', 'Telangana', true, 577),
('Jagtial', 'jagtial', 'Telangana', true, 578),
('Jangaon', 'jangaon', 'Telangana', true, 579),
('Jayashankar Bhoopalpally', 'jayashankar-bhoopalpally', 'Telangana', true, 580),
('Jogulamba Gadwal', 'jogulamba-gadwal', 'Telangana', true, 581),
('Kamareddy', 'kamareddy', 'Telangana', true, 582),
('Karimnagar', 'karimnagar', 'Telangana', true, 583),
('Khammam', 'khammam', 'Telangana', true, 584),
('Komaram Bheem Asifabad', 'komaram-bheem-asifabad', 'Telangana', true, 585),
('Mahabubabad', 'mahabubabad', 'Telangana', true, 586),
('Mahabubnagar', 'mahabubnagar', 'Telangana', true, 587),
('Mancherial', 'mancherial', 'Telangana', true, 588),
('Medak', 'medak', 'Telangana', true, 589),
('Medchal', 'medchal', 'Telangana', true, 590),
('Nagarkurnool', 'nagarkurnool', 'Telangana', true, 591),
('Nalgonda', 'nalgonda', 'Telangana', true, 592),
('Nirmal', 'nirmal', 'Telangana', true, 593),
('Nizamabad', 'nizamabad', 'Telangana', true, 594),
('Peddapalli', 'peddapalli', 'Telangana', true, 595),
('Rajanna Sircilla', 'rajanna-sircilla', 'Telangana', true, 596),
('Rangareddy', 'rangareddy', 'Telangana', true, 597),
('Sangareddy', 'sangareddy', 'Telangana', true, 598),
('Siddipet', 'siddipet', 'Telangana', true, 599),
('Suryapet', 'suryapet', 'Telangana', true, 600),
('Vikarabad', 'vikarabad', 'Telangana', true, 601),
('Wanaparthy', 'wanaparthy', 'Telangana', true, 602),
('Warangal (Rural)', 'warangal-rural-', 'Telangana', true, 603),
('Warangal (Urban)', 'warangal-urban-', 'Telangana', true, 604),
('Yadadri Bhuvanagiri', 'yadadri-bhuvanagiri', 'Telangana', true, 605),
('Dhalai', 'dhalai', 'Tripura', true, 606),
('Gomati', 'gomati', 'Tripura', true, 607),
('Khowai', 'khowai', 'Tripura', true, 608),
('North Tripura', 'north-tripura', 'Tripura', true, 609),
('Sepahijala', 'sepahijala', 'Tripura', true, 610),
('South Tripura', 'south-tripura', 'Tripura', true, 611),
('Unakoti', 'unakoti', 'Tripura', true, 612),
('West Tripura', 'west-tripura', 'Tripura', true, 613),
('Almora', 'almora', 'Uttarakhand', true, 614),
('Bageshwar', 'bageshwar', 'Uttarakhand', true, 615),
('Chamoli', 'chamoli', 'Uttarakhand', true, 616),
('Champawat', 'champawat', 'Uttarakhand', true, 617),
('Dehradun', 'dehradun', 'Uttarakhand', true, 618),
('Haridwar', 'haridwar', 'Uttarakhand', true, 619),
('Nainital', 'nainital', 'Uttarakhand', true, 620),
('Pauri Garhwal', 'pauri-garhwal', 'Uttarakhand', true, 621),
('Pithoragarh', 'pithoragarh', 'Uttarakhand', true, 622),
('Rudraprayag', 'rudraprayag', 'Uttarakhand', true, 623),
('Tehri Garhwal', 'tehri-garhwal', 'Uttarakhand', true, 624),
('Udham Singh Nagar', 'udham-singh-nagar', 'Uttarakhand', true, 625),
('Uttarkashi', 'uttarkashi', 'Uttarakhand', true, 626),
('Agra', 'agra', 'Uttar Pradesh', true, 627),
('Aligarh', 'aligarh', 'Uttar Pradesh', true, 628),
('Allahabad', 'allahabad', 'Uttar Pradesh', true, 629),
('Ambedkar Nagar', 'ambedkar-nagar', 'Uttar Pradesh', true, 630),
('Amethi (Chatrapati Sahuji Mahraj Nagar)', 'amethi-chatrapati-sahuji-mahraj-nagar-', 'Uttar Pradesh', true, 631),
('Amroha (J.P. Nagar)', 'amroha-j-p-nagar-', 'Uttar Pradesh', true, 632),
('Auraiya', 'auraiya', 'Uttar Pradesh', true, 633),
('Azamgarh', 'azamgarh', 'Uttar Pradesh', true, 634),
('Baghpat', 'baghpat', 'Uttar Pradesh', true, 635),
('Bahraich', 'bahraich', 'Uttar Pradesh', true, 636),
('Ballia', 'ballia', 'Uttar Pradesh', true, 637),
('Balrampur (UP)', 'balrampur-up', 'Uttar Pradesh', true, 638),
('Banda', 'banda', 'Uttar Pradesh', true, 639),
('Barabanki', 'barabanki', 'Uttar Pradesh', true, 640),
('Bareilly', 'bareilly', 'Uttar Pradesh', true, 641),
('Basti', 'basti', 'Uttar Pradesh', true, 642),
('Bhadohi', 'bhadohi', 'Uttar Pradesh', true, 643),
('Bijnor', 'bijnor', 'Uttar Pradesh', true, 644),
('Budaun', 'budaun', 'Uttar Pradesh', true, 645),
('Bulandshahr', 'bulandshahr', 'Uttar Pradesh', true, 646),
('Chandauli', 'chandauli', 'Uttar Pradesh', true, 647),
('Chitrakoot', 'chitrakoot', 'Uttar Pradesh', true, 648),
('Deoria', 'deoria', 'Uttar Pradesh', true, 649),
('Etah', 'etah', 'Uttar Pradesh', true, 650),
('Etawah', 'etawah', 'Uttar Pradesh', true, 651),
('Faizabad', 'faizabad', 'Uttar Pradesh', true, 652),
('Farrukhabad', 'farrukhabad', 'Uttar Pradesh', true, 653),
('Fatehpur', 'fatehpur', 'Uttar Pradesh', true, 654),
('Firozabad', 'firozabad', 'Uttar Pradesh', true, 655),
('Gautam Buddha Nagar', 'gautam-buddha-nagar', 'Uttar Pradesh', true, 656),
('Ghaziabad', 'ghaziabad', 'Uttar Pradesh', true, 657),
('Ghazipur', 'ghazipur', 'Uttar Pradesh', true, 658),
('Gonda', 'gonda', 'Uttar Pradesh', true, 659),
('Gorakhpur', 'gorakhpur', 'Uttar Pradesh', true, 660),
('Hamirpur (UP)', 'hamirpur-up', 'Uttar Pradesh', true, 661),
('Hapur (Panchsheel Nagar)', 'hapur-panchsheel-nagar-', 'Uttar Pradesh', true, 662),
('Hardoi', 'hardoi', 'Uttar Pradesh', true, 663),
('Hathras', 'hathras', 'Uttar Pradesh', true, 664),
('Jalaun', 'jalaun', 'Uttar Pradesh', true, 665),
('Jaunpur', 'jaunpur', 'Uttar Pradesh', true, 666),
('Jhansi', 'jhansi', 'Uttar Pradesh', true, 667),
('Kannauj', 'kannauj', 'Uttar Pradesh', true, 668),
('Kanpur Dehat', 'kanpur-dehat', 'Uttar Pradesh', true, 669),
('Kanpur Nagar', 'kanpur-nagar', 'Uttar Pradesh', true, 670),
('Kanshiram Nagar (Kasganj)', 'kanshiram-nagar-kasganj-', 'Uttar Pradesh', true, 671),
('Kaushambi', 'kaushambi', 'Uttar Pradesh', true, 672),
('Kushinagar (Padrauna)', 'kushinagar-padrauna-', 'Uttar Pradesh', true, 673),
('Lakhimpur - Kheri', 'lakhimpur-kheri', 'Uttar Pradesh', true, 674),
('Lalitpur', 'lalitpur', 'Uttar Pradesh', true, 675),
('Lucknow', 'lucknow', 'Uttar Pradesh', true, 676),
('Maharajganj', 'maharajganj', 'Uttar Pradesh', true, 677),
('Mahoba', 'mahoba', 'Uttar Pradesh', true, 678),
('Mainpuri', 'mainpuri', 'Uttar Pradesh', true, 679),
('Mathura', 'mathura', 'Uttar Pradesh', true, 680),
('Mau', 'mau', 'Uttar Pradesh', true, 681),
('Meerut', 'meerut', 'Uttar Pradesh', true, 682),
('Mirzapur', 'mirzapur', 'Uttar Pradesh', true, 683),
('Moradabad', 'moradabad', 'Uttar Pradesh', true, 684),
('Muzaffarnagar', 'muzaffarnagar', 'Uttar Pradesh', true, 685),
('Pilibhit', 'pilibhit', 'Uttar Pradesh', true, 686),
('Pratapgarh (UP)', 'pratapgarh-up', 'Uttar Pradesh', true, 687),
('RaeBareli', 'raebareli', 'Uttar Pradesh', true, 688),
('Rampur', 'rampur', 'Uttar Pradesh', true, 689),
('Saharanpur', 'saharanpur', 'Uttar Pradesh', true, 690),
('Sambhal (Bhim Nagar)', 'sambhal-bhim-nagar-', 'Uttar Pradesh', true, 691),
('Sant Kabir Nagar', 'sant-kabir-nagar', 'Uttar Pradesh', true, 692),
('Shahjahanpur', 'shahjahanpur', 'Uttar Pradesh', true, 693),
('Shamali (Prabuddh Nagar)', 'shamali-prabuddh-nagar-', 'Uttar Pradesh', true, 694),
('Shravasti', 'shravasti', 'Uttar Pradesh', true, 695),
('Siddharth Nagar', 'siddharth-nagar', 'Uttar Pradesh', true, 696),
('Sitapur', 'sitapur', 'Uttar Pradesh', true, 697),
('Sonbhadra', 'sonbhadra', 'Uttar Pradesh', true, 698),
('Sultanpur', 'sultanpur', 'Uttar Pradesh', true, 699),
('Unnao', 'unnao', 'Uttar Pradesh', true, 700),
('Varanasi', 'varanasi', 'Uttar Pradesh', true, 701),
('Alipurduar', 'alipurduar', 'West Bengal', true, 702),
('Bankura', 'bankura', 'West Bengal', true, 703),
('Birbhum', 'birbhum', 'West Bengal', true, 704),
('Burdwan (Bardhaman)', 'burdwan-bardhaman-', 'West Bengal', true, 705),
('Cooch Behar', 'cooch-behar', 'West Bengal', true, 706),
('Dakshin Dinajpur (South Dinajpur)', 'dakshin-dinajpur-south-dinajpur-', 'West Bengal', true, 707),
('Darjeeling', 'darjeeling', 'West Bengal', true, 708),
('Hooghly', 'hooghly', 'West Bengal', true, 709),
('Howrah', 'howrah', 'West Bengal', true, 710),
('Jalpaiguri', 'jalpaiguri', 'West Bengal', true, 711),
('Kalimpong', 'kalimpong', 'West Bengal', true, 712),
('Kolkata', 'kolkata', 'West Bengal', true, 713),
('Malda', 'malda', 'West Bengal', true, 714),
('Murshidabad', 'murshidabad', 'West Bengal', true, 715),
('Nadia', 'nadia', 'West Bengal', true, 716),
('North 24 Parganas', 'north-24-parganas', 'West Bengal', true, 717),
('Paschim Medinipur (West Medinipur)', 'paschim-medinipur-west-medinipur-', 'West Bengal', true, 718),
('Purba Medinipur (East Medinipur)', 'purba-medinipur-east-medinipur-', 'West Bengal', true, 719),
('Purulia', 'purulia', 'West Bengal', true, 720),
('South 24 Parganas', 'south-24-parganas', 'West Bengal', true, 721),
('Uttar Dinajpur (North Dinajpur)', 'uttar-dinajpur-north-dinajpur-', 'West Bengal', true, 722);
