-- Add expires_at to campaigns table
ALTER TABLE public.campaigns ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;

-- Update the types (though they are usually auto-generated by Supabase CLI, I'll update the local types.ts for consistency in my code analysis if needed, but best to keep migrations separate)
